/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RealEstateBuy } from "./RealEstateBuy";
export * as factories from "./factories";
export { RealEstateBuy__factory } from "./factories/RealEstateBuy__factory";
